# Common

input PageRequestInput {
  page: Int!
  size: Int!
}

# Admin Queries

extend type Query {

  # 관리자 회원 목록 조회
  adminMembers(
    page: PageRequestInput!
  ): AdminMemberPage!

  # 관리자 회원 상세 조회
  adminMember(
    memberId: ID!
  ): AdminMemberDetail!

  # 관리자 회원 로그인 이력 조회 (페이지네이션)
  adminLoginHistories(
    memberId: ID!
    page: PageRequestInput!
  ): AdminLoginHistoryPage!
}

# Admin Member Types

type AdminMemberPage {
  content: [AdminMember!]!
  totalElements: Int!
  totalPages: Int!
  pageNumber: Int!
  pageSize: Int!
  hasNext: Boolean!
  hasPrevious: Boolean!
  isFirst: Boolean!
  isLast: Boolean!
}

type AdminMember {
  memberId: ID!
  email: String!
  name: String!
  status: MemberStatus!
  role: String!
  regdate: String!
}

type AdminMemberDetail {
  memberId: ID!
  email: String!
  name: String!
  tel: String
  status: MemberStatus!
  role: String!
  emailVerified: Boolean!
  regdate: String!
}

# Admin Login History

type AdminLoginHistoryPage {
  content: [AdminLoginHistory!]!
  totalElements: Int!
  totalPages: Int!
  pageNumber: Int!
  pageSize: Int!
  hasNext: Boolean!
  hasPrevious: Boolean!
  isFirst: Boolean!
  isLast: Boolean!
}

type AdminLoginHistory {
  loginAt: String!
  ip: String
  device: String!
}
