scalar JSON
extend type Query {

    notesByStatus(
        sessionId: ID!
        status: CommonStatus!
        page: PageRequestInput!
    ): NotePage!

    noteDetail(noteId: ID!): NoteDetailResponseDTO

    allDeletedNotes(
        page: PageRequestInput!
    ): NotePage!
}

enum CommonStatus {
    ACTIVE
    ARCHIVED
    DELETED
    READY
}

type NotePage {
  content: [NoteResponseDTO!]!

  totalElements: Int!
  totalPages: Int!

  pageNumber: Int!
  pageSize: Int!

  hasNext: Boolean!
  hasPrevious: Boolean!

  isFirst: Boolean!
  isLast: Boolean!
}

type NoteResponseDTO {
    noteId: ID
    sessionId: ID
    title: String
    sourceType: String
    sourceId: ID
    status: String
    regdate: String
    moddate: String
    deletedAt: String
}

type NoteDetailResponseDTO {
    noteId: ID
    sessionId: ID
    title: String
    content: String
    summaryOption: JSON
    sourceType: String
    sourceId: ID
    status: String
    regdate: String
    moddate: String
    deletedAt: String
}