"""
회원 정보
"""
type Member {
    memberId: ID!
    email: String!
    name: String!
    tel: String
    profileImage: String
    status: String
    role: String
    emailVerified: Boolean
    regdate: String
    moddate: String
}

"""
회원가입 입력값
"""
input RegisterInput {
    email: String!
    password: String!
    name: String!
}

"""
GraphQL 로그인 응답 (토큰 반환용)
"""
type LoginResponse {
    member: Member!
    token: String!
}

"""
관리자 - 로그인 이력
(Java Entity: LoginHistory 기준)
"""
type AdminLoginHistory {
    loginHistoryId: ID!
    memberId: ID!
    ip: String!
    device: String!
    loginDate: String!
}

"""
Mutation 정의
"""
type Mutation {
    register(input: RegisterInput!): Member!
}

"""
Query 정의
"""
type Query {
    member(id: ID!): Member
    me: Member
    adminLoginHistory(memberId: ID!): [AdminLoginHistory!]!
    adminMembers(page: Int!, size: Int!): AdminMemberPage!

}

type AdminMemberPage {
    content: [Member!]!
    totalElements: Int!
    totalPages: Int!
    pageNumber: Int!
}