type Member {
    memberId: ID!
    email: String!
    name: String!
    tel: String
    profileImage: String
    status: String
    emailVerified: Boolean
    regdate: String
    moddate: String
}

input RegisterInput {
    email: String!
    password: String!
    name: String!
}

# ⭐ 로그인 응답 타입 추가
type LoginResponse {
    member: Member!
    token: String!
}

type Mutation {
    register(input: RegisterInput!): Member!

    # ⭐ login 반환 타입 변경
    login(email: String!, password: String!): LoginResponse!
}

type Query {
    member(id: ID!): Member
    me: Member
}



