server:
  port: 8080

spring:
  application:
    name: flocut_project

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    import:
      - optional:classpath:secret/db.yml
      - optional:classpath:secret/jwt.yml
      - optional:classpath:secret/mail.yml
      - optional:classpath:secret/oauth.yml
      - optional:classpath:secret/next.yml
      - optional:classpath:secret/solapi.yml
      - optional:classpath:secret/redis.yml
      - optional:classpath:secret/application.yml
      - optional:classpath:secret/openai.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  graphql:
    path: /graphql
    graphiql:
      enabled: false
